"""
Django settings for dat project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import logging
import django.utils.log
import logging.handlers

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')l$=w7h-l%jmpauz*0k#&!rzm52y94)k2luem9$j=wse$9go^n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dat_log_analysis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+'/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATICFILES_FINDERS = (
#     "django.contrib.staticfiles.finders.FileSystemFinder",
#     "django.contrib.staticfiles.finders.AppDirectoriesFinder"
# )

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
       'standard': {
            'format': '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s]- %(message)s'}  #日志格式 
    },
    'filters': {
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        # 'default': {
        #     'level':'DEBUG',
        #     'class':'logging.handlers.RotatingFileHandler',
        #     'filename': BASE_DIR + '/log/all.log',     #日志输出文件
        #     # 'maxBytes': 1024*1024*5,                  #文件大小 
        #     # 'backupCount': 5,                         #备份份数
        #     'formatter':'standard',                   #使用哪种formatters日志格式
        # },
        # 'error': {
        #     'level':'ERROR',
        #     'class':'logging.handlers.RotatingFileHandler',
        #     'filename': BASE_DIR + '/log/error.log',
        #     # 'maxBytes':1024*1024*5,
        #     # 'backupCount': 5,
        #     'formatter':'standard',
        # },
        # 'info': {
        #     'level':'INFO',
        #     'class':'logging.handlers.RotatingFileHandler',
        #     'filename': BASE_DIR + '/log/info.log',
        #     # 'maxBytes':1024*1024*5,
        #     # 'backupCount': 5,
        #     'formatter':'standard',
        # },
        # 'debug': {
        #     'level':'DEBUG',
        #     'class':'logging.handlers.RotatingFileHandler',
        #     'filename': BASE_DIR + '/log/debug.log',
        #     # 'maxBytes':1024*1024*5,
        #     # 'backupCount': 5,
        #     'formatter':'standard',
        # },
        'views_info': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR + '/log/views_info.log',
            # 'maxBytes':1024*1024*5,
            # 'backupCount': 5,
            'formatter':'standard',
        },
        'func_utils_info': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR + '/log/func_utils_info.log',
            # 'maxBytes':1024*1024*5,
            # 'backupCount': 5,
            'formatter':'standard',
        },
        'views_error': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR + '/log/views_error.log',
            # 'maxBytes':1024*1024*5,
            # 'backupCount': 5,
            'formatter':'standard',
        },
        'func_utils_error': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR + '/log/func_utils_error.log',
            # 'maxBytes':1024*1024*5,
            # 'backupCount': 5,
            'formatter':'standard',
        },
        'console':{
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
        'request_handler': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR + '/log/script.log', 
            # 'maxBytes': 1024*1024*5, 
            # 'backupCount': 5,
            'formatter':'standard',
        },
        'scprits_handler': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR + '/log/script.log', 
            # 'maxBytes': 1024*1024*5, 
            # 'backupCount': 5,
            'formatter':'standard',
        }
    },
    'loggers': {
        # 'django': {
        #     'handlers': ['default'],
        #     'level': 'DEBUG',
        #     'propagate': False 
        # },
        'django.request': {
            'handlers': ['request_handler'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'scripts': { 
            'handlers': ['scprits_handler'],
            'level': 'INFO',
            'propagate': False
        },
        'wms.wms_app.views_info': {
            'handlers': ['views_info'],
            'level': 'DEBUG',
            'propagate': True
        },
        'wms.wms_app.func_utils_info': {
            'handlers': ['func_utils_info'],
            'level': 'DEBUG',
            'propagate': True
        },
        'wms.wms_app.views_error': {
            'handlers': ['views_error'],
            'level': 'DEBUG',
            'propagate': True
        },
        'wms.wms_app.func_utils_error': {
            'handlers': ['func_utils_error'],
            'level': 'DEBUG',
            'propagate': True
        }
    } 
}